### ISSUE TITLE
[EPIC] Muon Regression tests

### ISSUE THREAD

**Issue by PraveenAsokan** [centrica-engineering/muon#104]
## Outcome

To confirm and capture the tests that we should do apart from unit and CI tests for the muon components and for beta release.

## Scope

 - [x] Setup the cypress automation for muon components
 - [x] Integrate cucumber with cypress
 - [x] Browserstack integration for cypress tests. https://github.com/centrica-engineering/muon/issues/205
 - [x] Add cypress tests to github action. https://github.com/centrica-engineering/muon/issues/228
 - [x] Build an app using muon components in different frameworks. https://github.com/centrica-engineering/muon/issues/4
 - [x] Create automation tests for the app using cypress and use it across frameworks
~~- [ ] Test the build scripts. https://github.com/centrica-engineering/muon/issues/110~~
 

We have integrated cucumber with cypress and completed the BDD and test steps for below components
 - [x] muon-cta
 - [x] muon-icon
 - [x] muon-inputter
 - [x] muon-detail
 - [x] muon-image
 - [x] muon-card
