### ISSUE TITLE
[Epic] Default app design for all frameworks

### ISSUE THREAD

**Issue by jholt1** [centrica-engineering/muon#152]
# Outcome

To design a journey that all frameworks can follow. This will allow for easy comparison and allow for a number of apps to be used for testing. Similar to https://todomvc.com/

# Scope

- [x] Decide the app journey
- [x] Create using a framework
- [x] Design user journey
- [x] Wireframe the first iteration of the example
- [x] consider using only existing components
- [ ] identify next candidates
- [x] create tests for the example

!! We are designing the component first, then we add it to the example app, to avoid designing for a cake company.

### Designing the app

- [x] [Task Model](https://3t2jkz.axshare.com/#id=0y6tmr&p=task_model&g=1) 
- [x] [User flow](https://3t2jkz.axshare.com/#id=rydm03&p=user_journey_-_iteration_2&g=1)
- [x] [Wireframe](https://3t2jkz.axshare.com/#id=gwd3mo&p=home__start_&g=1)

### Building the app

**Iteration 1:**
Breaking down the iteration in 4 steps of the journey: 

- [x] #213
- [x] #214
- [x] #215
- [x] #216

### Candidates for the next components
- `muon-form`: we'll need it to have functional forms (https://github.com/centrica-engineering/muon/issues/29)
- `muon-colunmns`: this will allow us to have more layout options (https://github.com/centrica-engineering/muon/issues/22)
- `muon-hero`: for the homepage (https://github.com/centrica-engineering/muon/issues/27)
- `muon-card`: to display options, frame content that needs a visual container (https://github.com/centrica-engineering/muon/issues/26)

**Comment by MekalaNagarajan-Centrica** [comment]
Closing as completed
