### ISSUE TITLE
Naming for component filenames

### ISSUE THREAD

**Issue by andij** [centrica-engineering/muon#290]
## Outcome

A naming convention for files contained within each components `/src` folder.

Prefix the tokens and styles files with the component name.

## Scope

- [x] Assess the size of a "search and replace" piece of work
- [x] Keep imports in mind (specially for css)
- [x] Amend all  build scripts referring to those files
- [x] mixins and directives should follow the same convention (`component-mixin.js`, `purpose-directive.js`) #346
- [x] Rename `styles.css` to `component-styles.css` #315 
- [x] Rename `token.json` to `design-tokens.json` and add `config-tokens.json` #337
- [x] Decide on convention for additional files located in each component's `/src` folder - https://github.com/centrica-engineering/muon/issues/290#issuecomment-1128888457
- [x] Document the naming convention for filenames In the handbook

## Notes

Each component has a `/src` folder and contained within is at least three files, `component.js`, `styles.css`, `token.json`.

Each `component.js` file has a prefix of the component name. For example `icon-component.js`.

This has proven to be useful when working on more than one component simultaneously. The same applies to the styles, tokens and any other files.

For example, when a component uses another component within, it's necessary to style this component for this context. E.g. the details component is consumed by the inputter. We have an additional styles.css called `inputter-styles-details.css`.

### Suggest rename

`packages/library/mixins/form-element-mixin.js` to `packages/library/mixins/form-mixin.js`

`packages/library/mixins/image-holder-mixin.js` to `packages/library/mixins/image-mixin.js`
