### ISSUE TITLE
[Epic] Examples area

### ISSUE THREAD

**Issue by jholt1** [centrica-engineering/muon#4]
## Outcome

To provide examples of the many ways to use the components, in setup, frameworks and different technologies.

## Scope

- [x] Decide on the examples (see first comment)
- [x] Understand how examples can be used for testing
- [x] Understand how examples can be kept up to date
- [ ] Internalisation
- [ ] #152

### Related to: 
- https://github.com/centrica-engineering/muon/issues/114

**Comment by MekalaNagarajan-Centrica** [comment]
Ember app examples are added. Closing the ticket. New ticket will be created when we examples are needed to add for new framework.
